version: "3"

services:
    app:
        image: my-brain-dump-app
        container_name: my-brain-dump-app
        build:
            context: .
            dockerfile: docker/Dockerfile
        depends_on:
            - redis
            - mysql
        env_file:
            - .docker.env
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        environment:
            APP_ENV: local
            CONTAINER_ROLE: app

    redis:
        container_name: my-brain-dump-cache
        image: redis:6-alpine
        ports:
            - "${REDIS_PORT}:6379"
        volumes:
            - redis:/data

    mysql:
        container_name: my-brain-dump-db
        image: mysql:8.0
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
    redis:
        driver: "local"
    mariadb:
        driver: "local"
